"project_id_env": CROWDIN_PROJECT_ID
"api_token_env": CROWDIN_TOKEN

files:
  - source: /lib/l10n/intl_en_US.arb
    translation: /lib/l10n/intl_%locale_with_underscore%.arb
  - source: /assets/credit/en.md
    translation: /assets/credit/%locale_with_underscore%.md
