name: Build Steps - Flutter common
description: Common steps for Flutter build

inputs:
  shell:
    required: true
  flutter-version:
    required: true
  flutter-channel:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: ${{ inputs.flutter-channel }}

    - name: Install Dependencies
      shell: ${{ inputs.shell }}
      run: flutter pub get

    - name: Generate Intermediates
      shell: ${{ inputs.shell }}
      run: |
        flutter pub run intl_utils:generate
        flutter pub run build_runner build --delete-conflicting-outputs
        dart run tools/gen_app_name.dart
        dart run tools/gen_locale_names.dart
