name: CI Build Test

on:
  push:
    branches:
      - ci_build_test

env:
  FLUTTER_VERSION: '3.16.9'
  FLUTTER_CHANNEL: 'stable'

jobs:
  build-with-windows:
    name: Build with Window
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Common Build Steps for Flutter
        uses: ./.github/actions/build-steps-flutter-common
        with:
          shell: pwsh
          flutter-version: ${{ env.FLUTTER_VERSION }}
          flutter-channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Build Steps for Windows
        uses: ./.github/actions/build-steps-win
        with:
          architecture: x64

  build-with-macos:
    name: Build with macOS
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Common Build Steps for Flutter
        uses: ./.github/actions/build-steps-flutter-common
        with:
          shell: bash
          flutter-version: ${{ env.FLUTTER_VERSION }}
          flutter-channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Build Steps for macOS
        uses: ./.github/actions/build-steps-macos

  build-with-linux:
    name: Build with Linux
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Common Build Steps for Flutter
        uses: ./.github/actions/build-steps-flutter-common
        with:
          shell: bash
          flutter-version: ${{ env.FLUTTER_VERSION }}
          flutter-channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Build Steps for Linux
        uses: ./.github/actions/build-steps-linux
        with:
          architecture: x64
          apt-arch: amd64
          appimage-arch: x86_64

  build-for-web:
    name: Build for web
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Build Steps for web
        uses: ./.github/actions/build-steps-web
        with:
          shell: bash
