name: Crowdin Action

on:
  push:
    branches:
      - master
  schedule:
    - cron: '27 */2 * * *'
  workflow_dispatch:

env:
  SCHEDULED_BRANCH: master
  FLUTTER_VERSION: '3.16.9'
  FLUTTER_CHANNEL: 'stable'

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    environment:
      name: crowdin
    steps:
      - name: Extract Branch Name
        if: ${{ github.event_name != 'schedule' }}
        run: echo "BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV

      - name: Set Branch For Scheduled Run
        if: ${{ github.event_name == 'schedule' }}
        run: echo "BRANCH=${SCHEDULED_BRANCH}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}

      - name: Always Fresh L10n Branch
        run: |
          git branch -D l10n_${{ env.BRANCH }} || true
          git checkout -b l10n_${{ env.BRANCH }}

      - name: Store Current HEAD
        run: echo "PRE_CROWDING_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Crowdin Action
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n_${{ env.BRANCH }}
          create_pull_request: true
          pull_request_title: 'New Crowdin Translations'
          pull_request_body: 'New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: ${{ env.BRANCH }}
          skip_ref_checkout: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Visit https://crowdin.com/settings#api-key to create this token
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

      - name: Store Post Crowding HEAD
        run: echo "POST_CROWDING_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Fix Branch
        if: ${{ env.PRE_CROWDING_COMMIT != env.POST_CROWDING_COMMIT }}
        run: |
          git checkout ${{ env.BRANCH }}
          git branch -D l10n_${{ env.BRANCH }}
          git fetch origin l10n_${{ env.BRANCH }}
          git checkout -b l10n_${{ env.BRANCH }} origin/l10n_${{ env.BRANCH }}

      - name: Common Build Steps for Flutter
        uses: ./.github/actions/build-steps-flutter-common
        if: ${{ env.PRE_CROWDING_COMMIT != env.POST_CROWDING_COMMIT }}
        with:
          shell: bash
          flutter-version: ${{ env.FLUTTER_VERSION }}
          flutter-channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Commit & Push changes
        uses: devops-infra/action-commit-push@master
        if: ${{ env.PRE_CROWDING_COMMIT != env.POST_CROWDING_COMMIT }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Generate Translation Files
