name: Generate Translation Files

on:
  push:
    branches:
      - l10n_*

env:
  FLUTTER_VERSION: '3.16.9'
  FLUTTER_CHANNEL: 'stable'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Common Build Steps for Flutter
        uses: ./.github/actions/build-steps-flutter-common
        with:
          shell: bash
          flutter-version: ${{ env.FLUTTER_VERSION }}
          flutter-channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Commit & Push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Generate Translation Files
