name: GitHub Pages

on:
  push:
    branches:
      - publish
      - ci_build_test

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Build Steps for web
        uses: ./.github/actions/build-steps-web
        with:
          shell: bash

  deploy:
    if: github.ref == 'refs/heads/publish'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
