name: GitHub Pages

on:
  push:
    branches:
      - publish
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.3

      - name: Dependency Override
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'pubspec.yaml'
          propertyPath: 'dependency_overrides.web'
          value: ^0.4.0
          commitChange: false

      - name: Install
        run: |
          mv web/index_3.22.3.html web/index.html
          flutter config --enable-web
          flutter pub get

      - name: Build
        run: flutter build web --wasm

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/publish'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
