name: GitHub Pages

on:
  push:
    branches:
      - publish

env:
  #FLUTTER_VERSION: '3.22.3'
  FLUTTER_VERSION: '3.16.9'
  FLUTTER_CHANNEL: 'stable'

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

#      - name: Dependency Override
#        uses: fjogeleit/yaml-update-action@main
#        with:
#          valueFile: 'pubspec.yaml'
#          changes: >-
#            {
#              "dependency_overrides.web":"^0.5.0",
#              "dependency_overrides.share_plus":"^8.0.2"
#            }
#          commitChange: false

      - name: Common Build Steps for Flutter
        uses: ./.github/actions/build-steps-flutter-common
        with:
          shell: bash
          flutter-version: ${{ env.FLUTTER_VERSION }}
          flutter-channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Prepare
        run: |
          #mv web/index_3.22.3.html web/index.html
          flutter config --enable-web

      - name: Build
#        run: flutter build web --wasm
        run: flutter build web

      - name: Upload artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/web/

  deploy:
    if: github.ref == 'refs/heads/publish'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
