name: "Build"

on:
  push:
    branches:
      - test

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      #1 Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

        #3 Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'

        #4 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

        #8 Build IPA ( IOS Build )
      - name: Build IPA
        run: flutter build ipa --no-codesign

      - name: Generate Unsigned IPA
        run: |
          cd build
          mkdir Payload
          mv ios/archive/Runner.xcarchive/Products/Applications/Runner.app Payload
          zip -r mset9_installer.ipa Payload

        #9 Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            build/mset9_installer.ipa
